const LAYER_DEPTHS = {
  GROUND: 0,
  OBJECTS_SHADOW: 1,
  OBJECTS: 2,
  PLAYER: 3,
  TOP_SHADOW: 4,
  TOP: 5,
  UI: 6,
};

const CHARACTER_STATES = {
  IDLE: "idle",
  WALK: "walk",
  ATTACK: "attack",
  ATTACK_WALK: "attack_walk",
  HIT: "hit",
  DYING: "dying",
  DEAD: "dead",
};

const CHARACTER_STATE_TRANSITIONS = {
  [CHARACTER_STATES.IDLE]: [
    CHARACTER_STATES.WALK,
    CHARACTER_STATES.ATTACK,
    CHARACTER_STATES.HIT,
    CHARACTER_STATES.DYING,
  ],
  [CHARACTER_STATES.WALK]: [
    CHARACTER_STATES.IDLE,
    CHARACTER_STATES.ATTACK,
    CHARACTER_STATES.HIT,
  ],
  [CHARACTER_STATES.ATTACK]: [
    CHARACTER_STATES.HIT,
    CHARACTER_STATES.DYING,
    CHARACTER_STATES.ATTACK_WALK,
    CHARACTER_STATES.ATTACK,
  ],
  [CHARACTER_STATES.HIT]: [
    CHARACTER_STATES.ATTACK,
    CHARACTER_STATES.ATTACK_WALK,
    CHARACTER_STATES.DYING,
  ],
  [CHARACTER_STATES.ATTACK_WALK]: [
    CHARACTER_STATES.ATTACK,
    CHARACTER_STATES.HIT,
    CHARACTER_STATES.DYING,
  ],
  [CHARACTER_STATES.DYING]: [
    CHARACTER_STATES.DEAD,
  ],
  [CHARACTER_STATES.DEAD]: [],
};

export { LAYER_DEPTHS, CHARACTER_STATES, CHARACTER_STATE_TRANSITIONS };
